# Generated by Django 5.0.1 on 2024-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='nutrition_images/')),
                ('age_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='days', max_length=10)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='vaccination_images/')),
                ('age_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='days', max_length=10)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedNutritionAndVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='days', max_length=10)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutrition', models.ManyToManyField(related_name='vaccination', to='recommendation.nutrition')),
                ('vaccination', models.ManyToManyField(related_name='nutrition', to='recommendation.vaccinations')),
            ],
        ),
        migrations.CreateModel(
            name='PlacesOfVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('map_url', models.URLField()),
                ('starting_time', models.TimeField(default='23:59:59')),
                ('ending_time', models.TimeField(default='23:59:59')),
                ('vaccine', models.ManyToManyField(related_name='places', to='recommendation.vaccinations')),
            ],
        ),
    ]
