# Generated by Django 4.2.9 on 2024-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_placesofvaccination_vaccination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesofvaccination',
            name='vaccination_date',
            field=models.DateField(default='2023-12-31'),
        ),
    ]
