# Generated by Django 4.2.9 on 2024-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_placesofvaccination_vaccination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='url_for_image',
            field=models.URLField(default='', verbose_name='only for development purposes'),
        ),
        migrations.AddField(
            model_name='vaccinations',
            name='url_for_image',
            field=models.URLField(default='', verbose_name='only for development purposes'),
        ),
    ]
